services:
  # default configuration for services in *this* file
  _defaults:
    # this means you cannot fetch services directly from the container via $container->get()
    # if you need to do this, you can override this setting on individual services
    autowire: true
    autoconfigure: true
    public: true

  nfl_fastr_symfony.resource_handler_service:
    class: HansPeterOrding\NflFastrSymfonyBundle\Service\ResourceHandlerService
    arguments:
      $temporaryLocalStorage: '@nflfastrsymfony.temporarystorage'
      $sources: [ ]

  HansPeterOrding\NflFastrSymfonyBundle\Service\ResourceHandlerService: '@nfl_fastr_symfony.resource_handler_service'

  nfl_fastr_symfony.import_service:
    class: HansPeterOrding\NflFastrSymfonyBundle\Service\ImportService

  nfl_fastr_symfony.import_roster_command:
    class: HansPeterOrding\NflFastrSymfonyBundle\Command\ImportNflFastr\ImportRosterCommand
    tags:
      - { name: 'console.command' }
    arguments:
      $importService: '@nfl_fastr_symfony.import_service'

  nfl_fastr_symfony.import_plays_command:
    class: HansPeterOrding\NflFastrSymfonyBundle\Command\ImportNflFastr\ImportPlaysCommand
    tags:
      - { name: 'console.command' }
    arguments:
      $importService: '@nfl_fastr_symfony.import_service'

  nfl_fastr_symfony.initialize_play_command:
    class: HansPeterOrding\NflFastrSymfonyBundle\Command\ImportNflFastr\Messenger\InitializePlayImportCommand
    tags:
      - { name: 'console.command' }
    arguments:
      $importService: '@nfl_fastr_symfony.import_service'

  nfl_fastr_symfony.initialize_roster_command:
    class: HansPeterOrding\NflFastrSymfonyBundle\Command\ImportNflFastr\Messenger\InitializeRosterImportCommand
    tags:
      - { name: 'console.command' }
    arguments:
      $importService: '@nfl_fastr_symfony.import_service'

  nfl_fastr_symfony.play_record_message_handler:
    class: HansPeterOrding\NflFastrSymfonyBundle\MessageHandler\PlayByPlayImport\ImportPlayRecordMessageHandler
    arguments:
      $importService: '@nfl_fastr_symfony.import_service'

  nfl_fastr_symfony.roster_record_message_handler:
    class: HansPeterOrding\NflFastrSymfonyBundle\MessageHandler\RosterImport\ImportRosterRecordMessageHandler
    arguments:
      $importService: '@nfl_fastr_symfony.import_service'

  HansPeterOrding\NflFastrSymfonyBundle\Repository\TeamRepository: ~
  HansPeterOrding\NflFastrSymfonyBundle\Repository\PlayerRepository: ~
  HansPeterOrding\NflFastrSymfonyBundle\Repository\RosterAssignmentRepository: ~
  HansPeterOrding\NflFastrSymfonyBundle\Repository\PlayRepository: ~
  HansPeterOrding\NflFastrSymfonyBundle\Repository\GameRepository: ~
  HansPeterOrding\NflFastrSymfonyBundle\Repository\DriveRepository: ~

  HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\PlayerConverterInterface:
    class: HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\PlayerConverter

  HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\TeamConverterInterface:
    class: HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\TeamConverter

  HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\RosterAssignmentConverterInterface:
    class: HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\RosterAssignmentConverter

  HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\GameConverterInterface:
    class: HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\GameConverter

  HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\DriveConverterInterface:
    class: HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\DriveConverter

  HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\FlagsConverterInterface:
    class: HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\FlagsConverter

  HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\PlayResultsConverterInterface:
    class: HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\PlayResultsConverter

  HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\YardsConverterInterface:
    class: HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\YardsConverter

  HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\ExpectedPointsConverterInterface:
    class: HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\ExpectedPointsConverter

  HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\WinProbabilitiesConverterInterface:
    class: HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\WinProbabilitiesConverter

  HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\PlayerAssignmentConverterInterface:
    class: HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\PlayerAssignmentConverter

  HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\TeamAssignmentConverterInterface:
    class: HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\TeamAssignmentConverter

  HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\PlayConverterInterface:
    class: HansPeterOrding\NflFastrSymfonyBundle\CsvConverter\PlayConverter

