HansPeterOrding\NflFastrSymfonyBundle\Entity\Player:
  type: entity
  lifecycleCallbacks:
    prePersist: [ updateLastUpdated ]
    postPersist: [ updateLastUpdated ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    firstName:
      type: string
      length: 255
    lastName:
      type: string
      length: 255
    birthDate:
      type: date_immutable
      nullable: true
    college:
      type: string
      length: 255
    highSchool:
      type: string
      length: 255
    gsisId:
      type: string
      nullable: true
      length: 255
    espnId:
      type: string
      nullable: true
      length: 255
    sportradarId:
      type: string
      nullable: true
      length: 255
    yahooId:
      type: string
      nullable: true
      length: 255
    rotowireId:
      type: string
      nullable: true
      length: 255
    headshotUrl:
      type: string
      length: 255
    lastUpdated:
      type: datetime
  embedded:
    height:
      class: HansPeterOrding\NflFastrSymfonyBundle\Entity\Player\Height
      columnPrefix: height_
    weight:
      class: HansPeterOrding\NflFastrSymfonyBundle\Entity\Player\Weight
      columnPrefix: weight_
  oneToMany:
    rosterAssignments:
      targetEntity: HansPeterOrding\NflFastrSymfonyBundle\Entity\RosterAssignment
      mappedBy: player
      cascade: [ 'all' ]
