HansPeterOrding\NflFastrSymfonyBundle\Entity\Team:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    abbreviation:
      type: string
      length: 3
    name:
      type: string
      length: 255
      nullable: true
    status:
      type: string
      length: 30
  oneToMany:
    rosterAssignments:
      targetEntity: HansPeterOrding\NflFastrSymfonyBundle\Entity\RosterAssignment
      mappedBy: team
      cascade: [ 'all' ]
